annotations:
  artifacthub.io/changes: |
    - kind: added
      description: "support custom pvc annotations for Zeebe"
    - kind: added
      description: "console sm alpha"
    - kind: fixed
      description: "moves ccsm spring profile outside of conditional"
    - kind: fixed
      description: "update to use initialContactPoints for Zeebe Gateway"
    - kind: fixed
      description: "update version matrix after latest bugfix releases"
    - kind: fixed
      description: "separated ingress status in helm notes"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/links: |
    - name: Camunda 8 docs
      url: https://docs.camunda.io/
    - name: Camunda 8 Self-Managed docs
      url: https://docs.camunda.io/docs/self-managed/about-self-managed/
    - name: Camunda 8 Self-Managed Helm charts
      url: https://github.com/camunda/camunda-platform-helm
apiVersion: v2
appVersion: 8.4.x
dependencies:
- condition: identity.enabled
  import-values:
  - child: image
    parent: global.identity.image
  name: identity
  repository: ""
  version: 9.2.0
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 19.19.3
- condition: postgresql.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 11.x.x
- name: common
  repository: https://charts.bitnami.com/bitnami
  version: 2.x.x
description: 'Camunda 8 Self-Managed Helm charts. Camunda''s process automation platform
  allows developers to design, automate and improve processes. '
home: https://docs.camunda.io/docs/self-managed/overview/
icon: https://helm.camunda.io/imgs/camunda.svg
keywords:
- bpm
- bpmn
- camunda-platform
- dmn
- process-engine
- workflow
maintainers:
- email: christopher.zell@camunda.com
  name: Zelldon
- email: ahmed.abouzaid@camunda.com
  name: aabouzaid
name: camunda-platform
sources:
- https://github.com/camunda/camunda-platform-helm
type: application
version: 9.2.0
